name: Actionlint

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

defaults:
  run:
    shell: bash -xeuo pipefail {0}

concurrency:
  group: "actionlint-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  workflow_syntax:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Install tools
        run: brew install actionlint shellcheck zizmor

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - run: zizmor .

      - run: actionlint
